import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is generated from the folder structure under `docs/`.
 * To add a new sample: drop a Markdown file into a category folder
 * (e.g. `docs/procedures/`) with `title` and `sidebar_position` frontmatter.
 * To add a new category: create a folder with a `_category_.json` file.
 */
const sidebars: SidebarsConfig = {
  samplesSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
